// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgtSydcqzKmKGrZi2weEx39uvSkDk6jgs',
    appId: '1:425113654617:web:0bcad244559517f4c12848',
    messagingSenderId: '425113654617',
    projectId: 'appforuser-3a161',
    authDomain: 'appforuser-3a161.firebaseapp.com',
    storageBucket: 'appforuser-3a161.firebasestorage.app',
    measurementId: 'G-FVTYJSNEKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-MFRdjpIxsyBsrQmLGTdDcBapaLZ7VhQ',
    appId: '1:425113654617:android:9688186eb0e5fac5c12848',
    messagingSenderId: '425113654617',
    projectId: 'appforuser-3a161',
    storageBucket: 'appforuser-3a161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvv-CndS1gqlwF5Qb6vFW9mBAY3O5myyg',
    appId: '1:425113654617:ios:35eaf04d0b62597bc12848',
    messagingSenderId: '425113654617',
    projectId: 'appforuser-3a161',
    storageBucket: 'appforuser-3a161.firebasestorage.app',
    androidClientId: '425113654617-8uitir69qif794a03umrqa5jukg74d3j.apps.googleusercontent.com',
    iosClientId: '425113654617-qbmdg7kcjnnbemug5ucr2a8okqfts7bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.easibite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvv-CndS1gqlwF5Qb6vFW9mBAY3O5myyg',
    appId: '1:425113654617:ios:35eaf04d0b62597bc12848',
    messagingSenderId: '425113654617',
    projectId: 'appforuser-3a161',
    storageBucket: 'appforuser-3a161.firebasestorage.app',
    androidClientId: '425113654617-8uitir69qif794a03umrqa5jukg74d3j.apps.googleusercontent.com',
    iosClientId: '425113654617-qbmdg7kcjnnbemug5ucr2a8okqfts7bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.easibite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZV6O8FKYWzAjD48FvtzEEi4A4WUDvMeg',
    appId: '1:425113654617:web:01bdd5ff1faf8818c12848',
    messagingSenderId: '425113654617',
    projectId: 'appforuser-3a161',
    authDomain: 'appforuser-3a161.firebaseapp.com',
    storageBucket: 'appforuser-3a161.firebasestorage.app',
    measurementId: 'G-CELBM2DSDB',
  );
}
